In [1]:
import numpy as np

In [3]:
df = np.loadtxt('https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv'
                , delimiter = ',')

In [4]:
df

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [6]:
df.shape

(768, 9)

In [9]:
# input data
x = df[:,:8]

# output data
y = df[:,8]

In [11]:
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [12]:
y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [14]:
# For counting 1:(+ve) and 0:(-ve) for diabeties
from collections import Counter
Counter(y)

Counter({1.0: 268, 0.0: 500})

In [18]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [19]:
model = Sequential()

In [21]:
# input layer
model.add(Dense(12, input_dim=8, activation='relu'))

# hidden layer
model.add(Dense(8, activation='relu'))
model.add(Dense(8, activation='relu'))

# outout layer
# sigmoid is for binary classification
# softmax is for multi-class classification
model.add(Dense(1, activation='sigmoid'))

In [23]:
model.compile(loss='binary_crossentropy', optimizer='adam',
              metrics=['accuracy'])

In [25]:
# Train the model
model.fit(x, y, epochs=100, batch_size=10)

Epoch 1/100
77/77 [==============================] - 0s 3ms/step - loss: 0.4843 - accuracy: 0.7539
Epoch 2/100
77/77 [==============================] - 0s 3ms/step - loss: 0.4898 - accuracy: 0.7656
Epoch 3/100
77/77 [==============================] - 0s 2ms/step - loss: 0.5015 - accuracy: 0.7500
Epoch 4/100
77/77 [==============================] - 0s 3ms/step - loss: 0.4817 - accuracy: 0.7747
Epoch 5/100
77/77 [==============================] - 0s 2ms/step - loss: 0.4912 - accuracy: 0.7604
Epoch 6/100
77/77 [==============================] - 0s 3ms/step - loss: 0.4783 - accuracy: 0.7604
Epoch 7/100
77/77 [==============================] - 0s 2ms/step - loss: 0.4757 - accuracy: 0.7826
Epoch 8/100
77/77 [==============================] - 0s 3ms/step - loss: 0.4688 - accuracy: 0.7708
Epoch 9/100
77/77 [==============================] - 0s 2ms/step - loss: 0.4768 - accuracy: 0.7721
Epoch 10/100
77/77 [==============================] - 0s 2ms/step - loss: 0.4767 - accuracy: 0.7773
Epoch 11/

In [26]:
# Evaluate the model
model.evaluate(x,y)

24/24 [==============================] - 0s 2ms/step - loss: 0.3966 - accuracy: 0.8099


[0.3965916335582733, 0.8098958134651184]

In [27]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 12)                108       
                                                                 
 dense_1 (Dense)             (None, 12)                156       
                                                                 
 dense_2 (Dense)             (None, 8)                 104       
                                                                 
 dense_3 (Dense)             (None, 8)                 72        
                                                                 
 dense_4 (Dense)             (None, 1)                 9         
                                                                 
Total params: 449 (1.75 KB)
Trainable params: 449 (1.75 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
